// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlataformaNexbank.Infrastructure.Persistence;

#nullable disable

namespace PlataformaNexbank.Infrastructure.Migrations
{
    [DbContext(typeof(NexBankDbContext))]
    [Migration("20261001022708_AdicionaTitularECpf")]
    partial class AdicionaTitularECpf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlataformaNexbank.Domain.Entities.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("PlataformaNexbank.Domain.Entities.ContaBancaria", b =>
                {
                    b.OwnsOne("PlataformaNexbank.Domain.ValueObjects.Dinheiro", "Saldo", b1 =>
                        {
                            b1.Property<Guid>("ContaBancariaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Moeda");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Saldo");

                            b1.HasKey("ContaBancariaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaBancariaId");
                        });

                    b.OwnsMany("PlataformaNexbank.Domain.Entities.Transacao", "Transacoes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContaBancariaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Data")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContaBancariaId");

                            b1.ToTable("TransacaoHistorico", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContaBancariaId");

                            b1.OwnsOne("PlataformaNexbank.Domain.ValueObjects.Dinheiro", "Valor", b2 =>
                                {
                                    b2.Property<int>("TransacaoId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Moeda")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("Moeda");

                                    b2.Property<decimal>("Valor")
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("Valor");

                                    b2.HasKey("TransacaoId");

                                    b2.ToTable("TransacaoHistorico");

                                    b2.WithOwner()
                                        .HasForeignKey("TransacaoId");
                                });

                            b1.Navigation("Valor")
                                .IsRequired();
                        });

                    b.OwnsOne("PlataformaNexbank.Domain.ValueObjects.Titular", "Titular", b1 =>
                        {
                            b1.Property<Guid>("ContaBancariaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("TitularNome");

                            b1.HasKey("ContaBancariaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaBancariaId");

                            b1.OwnsOne("PlataformaNexbank.Domain.ValueObjects.Cpf", "Cpf", b2 =>
                                {
                                    b2.Property<Guid>("TitularContaBancariaId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("Cpf");

                                    b2.HasKey("TitularContaBancariaId");

                                    b2.HasIndex("Numero")
                                        .IsUnique()
                                        .HasDatabaseName("IX_Contas_Cpf");

                                    b2.ToTable("Contas");

                                    b2.WithOwner()
                                        .HasForeignKey("TitularContaBancariaId");
                                });

                            b1.Navigation("Cpf")
                                .IsRequired();
                        });

                    b.Navigation("Saldo")
                        .IsRequired();

                    b.Navigation("Titular")
                        .IsRequired();

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
