@PlataformaNexbank.Api_HostAddress = http://localhost:5039

### Criar conta
POST {{PlataformaNexbank.Api_HostAddress}}/contas
Content-Type: application/json

{
  "titular": "Thiago"
}

###

### Buscar conta (troque {id} pelo Id ao criar uma conta, apenas teste)
GET {{PlataformaNexbank.Api_HostAddress}}/contas/{id}
Accept: application/json

###