@PlataformaNexbank.Api_HostAddress = http://localhost:5039

### Criar conta
POST {{PlataformaNexbank.Api_HostAddress}}/contas
Content-Type: application/json

{
  "titular": "Thiago Murilo"
}

###

### Buscar conta (troque o Guid abaixo pelo Id retornado ao criar a conta)
GET {{PlataformaNexbank.Api_HostAddress}}/contas/0be0a0e5-1930-404b-9c4c-c02e895d906d
Accept: application/json

###

### Depositar
POST {{PlataformaNexbank.Api_HostAddress}}/contas/0be0a0e5-1930-404b-9c4c-c02e895d906d/depositar
Content-Type: application/json

{
  "valor": 100
}

###

### Sacar
POST {{PlataformaNexbank.Api_HostAddress}}/contas/0be0a0e5-1930-404b-9c4c-c02e895d906d/sacar
Content-Type: application/json

{
  "valor": 30
}

###

### Histórico de transações
GET {{PlataformaNexbank.Api_HostAddress}}/contas/489d8b5c-9430-4a05-a003-cb1a2799ee97/transacoes
Accept: application/json