<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\PlataformaNexbank.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\PlataformaNexbank.Infrastructure.csproj" />
  </ItemGroup>
	
</Project>
